### ISSUE TITLE
About the classifiers

### ISSUE THREAD

**Issue by mingliangzhang2018** [FPNAS/ResLT#1]
Thanks for proposing such interesting method. I am wondering three branches have diffierent classifiers or same?
Furthermore, do you compare with mulit-experts methods as [1]?
[1] LONG-TAILED RECOGNITION BY ROUTING DIVERSE DISTRIBUTION-AWARE EXPERTS, 2021 ICLR.

**Comment by jiequancui** [comment]
Hi,

We use only the shared same classifier.
Our method is complementary to the ensemble-based method [1]. A careful comparison will be added in our new version.

**Comment by mingliangzhang2018** [comment]
Could you describe in detail how to divide different classes according to different branches? Each group has the same imbalance factor?  If one bach size has no tail classes, the tail branch would do not work? Thank you very much.

**Comment by jiequancui** [comment]
Hi,

Please refer to Sec. 3 in the paper for assigning classes to different branches.
If one batch has no tail classes image in the training process, the L_{t} will be 0, but L_{all} will work normally.
