### ISSUE TITLE
Why 1x1 Conv can be replaced with BN layer?

### ISSUE THREAD

**Issue by machengcheng2016** [FPNAS/ResLT#10]
Greetings
Really nice work, but I have a small question.
You mentioned in the code comments that `# 1x1 conv can be replaced with more light-weight bn layer`, I wonder why they are equivalent? Actually I think conv and bn are totally different.

**Comment by jiequancui** [comment]
Hi,

Thanks for your interest in our work.

1x1 conv is not equivalent to a bn layer. Here I just want to stress that the branch network can be much light-weight.

Best,
Jiequan

**Comment by machengcheng2016** [comment]
Thanks for your quick reply! Now I see :)
Have you ever tried to apply 1x1 conv instead of bn in your experiments? Does bn yield better performances or just similar?

**Comment by jiequancui** [comment]
HI,

1x1 conv and bn show similar results.

**Comment by machengcheng2016** [comment]
ok, thank u 😄
