### ISSUE TITLE
Variables are not defined in the code

### ISSUE THREAD

**Issue by betterpig123** [FPNAS/ResLT#6]
Sorry to bother you that 

Code is incomplete, train_sampler is not defined in ImageNetTrain， And Can you explain root_path，dataset，data_path to me

Looking forward to your reply

**Comment by jiequancui** [comment]
Hi, 

We use Dataparallel for multi-GPU training. Please use the training script provided by us.

The root_path is the directory where to store your training log and checkpoints. data_path is the directory for ImageNet.

You can try to run the code and get some feelings.
